### ISSUE TITLE
data-index CrashLoopBackOff on kubernetes

### ISSUE THREAD

**Issue by rbaumgar** [kiegroup/kogito-operator#824]
looks like the same problem as #607 

OpenShift 4.7
Infinispan Operator 2.1.3
Kogito 1.4.0
Strimzi 0.22.1

```
$ kogito install infra kogito-infinispan-infra --kind Infinispan --apiVersion infinispan.org/v1
$ kogito install infra kogito-kafka-infra --kind Kafka --apiVersion kafka.strimzi.io/v1beta1
$ kogito install data-index --infra kogito-infinispan-infra --infra kogito-kafka-infra

$ oc logs kogito-infinispan-0
...
2021-03-30 10:58:42,302 WARN  [io.qua.qut.run.ContentTypes] (main) Unable to detect the content type for templates/jgroups-encrypt; using application/octet-stream
2021-03-30 10:58:42,304 INFO  [io.quarkus] (main) config-generator 2.1.3.Final native (powered by Quarkus 1.7.6.Final) started in 0.012s. 
2021-03-30 10:58:42,304 INFO  [io.quarkus] (main) Profile prod activated. 
2021-03-30 10:58:42,304 INFO  [io.quarkus] (main) Installed features: [cdi, qute]
2021-03-30 10:58:42,646 INFO  [io.quarkus] (main) config-generator stopped in 0.001s

10:58:48,241 INFO  (main) [BOOT] JVM OpenJDK 64-Bit Server VM Red Hat, Inc. 11.0.10+9-LTS
10:58:48,329 INFO  (main) [BOOT] JVM arguments = [-server, -Xmx200M, -Xms200M, -XX:MaxRAM=420M, -Dsun.zip.disableMemoryMapping=true, -XX:+UseSerialGC, -XX:MinHeapFreeRatio=5, -XX:MaxHeapFreeRatio=10, -XX:+ExitOn
OutOfMemoryError, -XX:MetaspaceSize=32m, -XX:MaxMetaspaceSize=96m, -Djava.net.preferIPv4Stack=true, -Djava.awt.headless=true, -Dvisualvm.display.name=infinispan-server, -Djava.util.logging.manager=org.apache.log
ging.log4j.jul.LogManager, -Dinfinispan.server.home.path=/opt/infinispan, -classpath, :/opt/infinispan/boot/infinispan-server-runtime-12.0.2.Final-loader.jar, org.infinispan.server.loader.Loader, org.infinispan.
server.Bootstrap]
10:58:48,329 INFO  (main) [BOOT] PID = 100
10:58:48,528 INFO  (main) [org.infinispan.SERVER] ISPN080000: Infinispan Server starting
10:58:48,528 INFO  (main) [org.infinispan.SERVER] ISPN080017: Server configuration: infinispan.xml
10:58:48,528 INFO  (main) [org.infinispan.SERVER] ISPN080032: Logging configuration: /opt/infinispan/server/conf/log4j2.xml
10:58:52,826 INFO  (main) [org.wildfly.openssl.SSL] WFOPENSSL0002 OpenSSL Version OpenSSL 1.1.1g FIPS  21 Apr 2020
10:58:52,828 INFO  (main) [org.infinispan.SECURITY] ISPN000946: Using OpenSSL Provider
10:58:53,828 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'query-dsl-filter-converter-factory'
10:58:53,828 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'continuous-query-filter-converter-factory'
10:58:53,831 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'iteration-filter-converter-factory'
10:58:53,833 INFO  (main) [org.infinispan.SERVER] ISPN080027: Loaded extension 'jdk.nashorn.api.scripting.NashornScriptEngineFactory'
10:58:55,933 INFO  (main) [org.infinispan.CONTAINER] ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
10:58:56,835 WARN  (main) [org.infinispan.PERSISTENCE] ISPN000554: jboss-marshalling is deprecated and planned for removal
10:58:59,840 INFO  (main) [org.infinispan.query.remote.impl.ProtobufMetadataManagerImpl] ISPN028019: Registering protostream serialization context initializer: org.infinispan.query.core.stats.impl.PersistenceCon
textInitializerImpl
10:58:59,842 INFO  (main) [org.infinispan.CONTAINER] ISPN000128: Infinispan version: Infinispan 'Lockdown' 12.0.2.Final
10:59:00,843 INFO  (main) [org.infinispan.CLUSTER] ISPN000078: Starting JGroups channel kogito-infinispan with stack image-tcp
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.infinispan.commons.util.Util (file:/opt/infinispan/lib/infinispan-commons-12.0.2.Final.jar) to constructor com.sun.jndi.dns.DnsContextFactory()
WARNING: Please consider reporting this to the maintainers of org.infinispan.commons.util.Util
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:59:03,748 INFO  (main) [org.infinispan.CLUSTER] ISPN000094: Received new cluster view for channel kogito-infinispan: [kogito-infinispan-0-39206|0] (1) [kogito-infinispan-0-39206]
10:59:03,757 INFO  (main) [org.infinispan.CLUSTER] ISPN000079: Channel kogito-infinispan local address is kogito-infinispan-0-39206, physical addresses are [10.129.3.156:7800]
10:59:03,933 INFO  (main) [org.infinispan.CONTAINER] ISPN000390: Persisted state, version=12.0.2.Final timestamp=2021-03-30T10:59:03.929226Z
10:59:05,135 INFO  (main) [org.jboss.threads] JBoss Threads version 2.3.3.Final
10:59:05,444 INFO  (main) [org.infinispan.CONTAINER] ISPN000104: Using EmbeddedTransactionManager
10:59:07,635 INFO  (main) [org.infinispan.server.core.RequestTracer] OpenTracing integration is disabled
10:59:08,337 INFO  (ForkJoinPool.commonPool-worker-3) [org.infinispan.SERVER] ISPN080018: Started connector HotRod (internal)
10:59:08,844 INFO  (main) [org.infinispan.SERVER] ISPN080018: Started connector REST (internal)
10:59:09,463 INFO  (main) [org.infinispan.SERVER] ISPN080004: Connector SINGLE_PORT (default) listening on 10.129.3.156:11222
10:59:09,527 INFO  (main) [org.infinispan.SERVER] ISPN080034: Server 'kogito-infinispan-0-39206' listening on https://10.129.3.156:11222
10:59:09,632 INFO  (main) [org.infinispan.SERVER] ISPN080018: Started connector REST (internal)
10:59:09,635 INFO  (main) [org.infinispan.SERVER] ISPN080004: Connector SINGLE_PORT (admin) listening on 10.129.3.156:11223
10:59:09,636 INFO  (main) [org.infinispan.SERVER] ISPN080034: Server 'kogito-infinispan-0-39206' listening on http://10.129.3.156:11223
10:59:09,636 INFO  (main) [org.infinispan.SERVER] ISPN080001: Infinispan Server 12.0.2.Final started in 21106ms
10:59:26,012 WARN  (blocking-thread--p3-t1) [org.infinispan.CONFIG] ISPN000586: The memory configuration element 'off-heap' has been deprecated. Please update your configuration
10:59:26,054 WARN  (blocking-thread--p3-t2) [org.infinispan.encoding.impl.StorageConfigurationManager] ISPN000599: Configuration for cache 'default' does not define the encoding for keys or values. If you use op
erations that require data conversion or queries, you should configure the cache with a specific MediaType for keys or values.
11:01:36,528 WARN  (SINGLE_PORT-ServerIO-4-1) [io.netty.handler.ssl.ApplicationProtocolNegotiationHandler] [id: 0xc0ddf788, L:/10.129.3.156:11222 ! R:/10.129.3.160:54292] TLS handshake failed: io.netty.handler.s
sl.NotSslRecordException: not an SSL/TLS record: a0031e21000003ffffffff0f0000
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1261)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:515)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.infinispan.server.core.transport.StatsChannelHandler.channelRead(StatsChannelHandler.java:26)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

11:01:36,552 WARN  (SINGLE_PORT-ServerIO-4-2) [io.netty.handler.ssl.ApplicationProtocolNegotiationHandler] [id: 0x7c863f16, L:/10.129.3.156:11222 ! R:/10.129.3.160:54300] TLS handshake failed: io.netty.handler.s
sl.NotSslRecordException: not an SSL/TLS record: a0051e21000003ffffffff0f0000

```

**Comment by sutaakar** [comment]
Hello @rbaumgar 

Infinispan Operator 2.1.3 is not yet supported for Kogito, can you please try to use Data index with Infinispan Operator 2.0.6?

**Comment by rbaumgar** [comment]
@sutaakar 
you are right. I have tried with v1 unsuccessful. But 2.0.6 works fine. Did I miss somewhere the documentation/hint?
